# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iSSLocation' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iSSLocation
  pod 'Mapbox-iOS-SDK', '~> 4.2'

  target 'iSSLocationTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iSSLocationUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
